# Generated by Django 4.2.1 on 2023-07-11 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
