# Generated by Django 4.2.1 on 2023-07-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subscribe_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.partner'),
        ),
    ]
