# Generated by Django 4.2.1 on 2023-12-26 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_verification',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
