# Generated by Django 4.2.1 on 2023-12-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_verification_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_id', models.CharField(default='', editable=False, max_length=8, unique=True)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Privacy_Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_id', models.CharField(default='', editable=False, max_length=8, unique=True)),
                ('privacy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Return_Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(default='', editable=False, max_length=8, unique=True)),
                ('return_policy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Terms_Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_id', models.CharField(default='', editable=False, max_length=8, unique=True)),
                ('terms', models.TextField()),
            ],
        ),
    ]
