# Generated by Django 4.2.1 on 2024-01-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_about_privacy_policy_return_policy_terms_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(default='', editable=False, max_length=8, unique=True)),
                ('video', models.FileField(upload_to='video/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
